### PR TITLE
FIX - 114: Multiple device fix

### PR DESCRIPTION
**Pull request by k00k**
- fixes issue 114: Speakers appear multiple times
- updated the sonos module to ~0.8.0 (0.8.0)
- replace forEach with sonos module search's DeviceAvailable listener to find all available for iteration
- updated diagnostics.js to use DeviceAvailable listener also
- only VERY LIGHTLY tested, please beat it up.

### CODE REVIEW

**Comment by justintime** [comment]
I just tested this, and my paired devices show up twice.

**Comment by k00k** [comment]
Unfortunately, I only have a Sonos Play 1 and a Connect on a receiver, so I can't test the pairing aspect. If I had to guess, this is probably an issue in the node-sonos module. If anyone knows of a way that I can simulate the pairing functionality and thus its duplication, please holler.

**Comment by nraamat** [comment]
It seems to stem from the fact that node-sonos uses the UDP protocol without filtering/keeping track of responses. In UDP there are no guarantees that broadcast and answers will not be duplicated in the network.

**Comment by k00k** [comment]
@nraamat that makes sense. I guess there will need to be some dupe filtering on this end. I'll leave that to @stephen if he's still active. Otherwise I could take a look.

**Comment by justintime** [comment]
UDP shouldn't reliably dupe packets like that *every* time, I wonder if it has something to do with the mesh topology.  Perhaps each device advertises not only itself, but all the other nodes it's aware of?  Either way, the fix is the same I think.

I'm guessing that right about [here](https://github.com/stephen/node-sonos/blob/stephen-1.0.0/lib/logicalDevice.js#L89), we could just check to see if the current host:port combination has been already discovered.  If it has, just skip to the next device.

Thoughts on that approach?

**Comment by nraamat** [comment]
@justintime MESH topology could be the reason, I was also quite puzzled with how frequent it happened. However, I already implemented the fix you suggested - just need to finalize it and make a PR

**Comment by k00k** [comment]
Does it make sense to hold off until https://github.com/bencevans/node-sonos/pull/55 gets integrated?

**Comment by justintime** [comment]
@nraamat perfect!  I'll test once you make the PR.  Make sure you reference this issue from it so we get notified.

@k00k This bug was introduced in bencevans/node-sonos#55 so in my opinion, the merge is blocked until we fix this duplication bug.  If we can get this merged back into bencevans/node-sonos, then we should be able to make a PR for stephen/airsonos to go back to using upstream node-sonos rather than @stephen's fork of it.

**Comment by lirenzhu** [comment]
Fix for this issue should be in node-sonos, referencing stephen/node-sonos#1 here.

**Comment by stephen** [comment]
Merged https://github.com/stephen/node-sonos/pull/1 - reinstallation should solve this.

**Pull request closed without merging**
